name: Docker test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker lint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
          failure-threshold: error

      - name: Build Docker Image
        run: docker build -t python-game-image .

      - name: Run tests
        run: |
          docker run --name python-game-container python-game-image
          docker exec python-game-container entrypoint
          docker exec python-game-container python /python-game/app.py > test-results.txt
          docker stop python-game-container

      - name: Check no-root inside
        id: root
        continue-on-error: true
        run: |
          docker exec python-game-container whoami
          docker exec python-game-container su -

      - name: Upload test results
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test-results.txt

      - name: Slack Notification on Success
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github_action
          SLACK_COLOR: '#006400'
          SLACK_ICON: 'https://github.com/rtCamp.png?size=48'
          SLACK_MESSAGE: 'Python game docker tested successfully!'
          SLACK_TITLE: 'SUCCESS! No root access inside the container.'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification on Failure
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: github_action
          SLACK_COLOR: '#8B0000'
          SLACK_ICON: 'https://github.com/rtCamp.png?size=48'
          SLACK_MESSAGE: 'Failure test python docker game'
          SLACK_TITLE: 'FAILURE! User is ROOT inside the container!'
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
